/* ============================================================ */
/* Learn from examples		                                    */
/* ============================================================ */

/*
Although we have only covered a small set of tools:
- Oscillators
- Envelopes
- Filters

We are actually equipped to make a huge range of synths

Have a look through some of the files in the examples folder

Also have a look at the examples folder in Applications/Supercollider/examples
*/

