/* ============================================================ */
/* Building Synths 			                                    */
/* ============================================================ */

/*
Although we have only covered a small set of tools:
- Oscillators
- Envelopes
- Filters

We are actually equipped to make a huge range of synths

We're going to look at a few examples from the examples folder.
*/